version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: travelbuddy-db
    environment:
      POSTGRES_DB: travel_buddy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: travelbuddy-app
    ports:
      - "8080:8080"
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/travel_buddy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    depends_on:
      - db

volumes:
  pgdata:
