---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/api/trips":
    get:
      tags:
        - trip-controller
      operationId: getTrips
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  type: object
    post:
      tags:
        - trip-controller
      operationId: createNewTrip
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Trip"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Trip"
  "/api/trips/{id}/budget":
    post:
      tags:
        - trip-controller
      operationId: addBudget
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: expenseName
          in: query
          required: true
          schema:
            type: string
        - name: totalAmount
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/TripBudget"
  "/api/trips/{id}/apply":
    post:
      tags:
        - trip-controller
      operationId: applyForTrip
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/TripApplication"
  "/api/register":
    post:
      tags:
        - trip-controller
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/User"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/User"
  "/api/login":
    post:
      tags:
        - trip-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AuthRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/AuthResponse"
  "/trips":
    get:
      tags:
        - trip-controller
      operationId: showTripsPage
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: string
  "/login":
    get:
      tags:
        - trip-controller
      operationId: showLoginPage
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: string
components:
  schemas:
    Trip:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fromPlace:
          type: string
        toPlace:
          type: string
        departureDate:
          type: string
          format: date-time
        totalSeats:
          type: integer
          format: int32
        availableSeats:
          type: integer
          format: int32
        description:
          type: string
        driver:
          "$ref": "#/components/schemas/User"
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        password:
          type: string
        fullName:
          type: string
        age:
          type: integer
          format: int32
        contactInfo:
          type: string
        role:
          type: string
    TripBudget:
      type: object
      properties:
        id:
          type: integer
          format: int64
        expenseName:
          type: string
        totalAmount:
          type: number
        amountPerPerson:
          type: number
        trip:
          "$ref": "#/components/schemas/Trip"
    TripApplication:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
        reactedAt:
          type: string
          format: date-time
        trip:
          "$ref": "#/components/schemas/Trip"
        passenger:
          "$ref": "#/components/schemas/User"
    AuthRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        token:
          type: string
